---
- name: "Prepare Mailhog"
  apt:
    name: build-essential
    state: present
  when: mailhog_enabled
  tags: [mailhog]

- name: "Render enviroment variables"
  template:
    src: "mailhog.env.j2"
    dest:  "{{ mailhog_install_dir }}/mailhog/env"
  when:
    - mailhog_enviroment_vars is defined
  tags: [mailhog, env]

- name: "Enable Mailhog"
  include_role:
    name: geerlingguy.mailhog
  when: mailhog_enabled
  tags: [mailhog]

- name: "Configure basic auth"
  include_tasks: basic_auth.yml
  when: mailhog_basic_auth_enabled
  tags: [mailhog, basic-auth]

